name: CI

# Controls when the action will run.
on:
    release:
        types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy-latest-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 #Otherwise, you will fail to push refs to dest
            - name: Write version to file
              env:
                  VERSION: ${{ github.event.release.tag_name }}
              run: |
                  echo "$VERSION" > version
            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m "Auto updating version-file" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  force: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy
              run: curl ${{ secrets.ENVOYER_HOOK }}
            
            - name: twitter
              uses: ethomson/send-tweet-action@v1
              with:
                  status: "A new version of https://public-talk.jwapp.info (${{github.event.release.tag_name}}) has just been launched.\n${{github.event.release.body}}"
                  consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
                  consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
                  access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                  access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    